# Introduction to NumPy
This notebook introduces the NumPy library and demonstrates common array creation, indexing, random number generation, arithmetic, and linear algebra operations. **All code cells are left unchanged.**

In [1]:
import numpy as np

## Creating an Array of Zeros
`np.zeros(shape)` creates a new NumPy array filled entirely with zeros. Here, a one-dimensional array of length **5** is created.

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

## Creating an Array of Ones
`np.ones(shape)` returns an array whose elements are all initialized to **1**.

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

## Filling an Array with a Constant Value
`np.full(shape, fill_value)` creates an array where every element has the specified value. This example fills an array of length **10** with `2.5`.

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

## Creating Arrays from Python Lists
`np.array()` converts standard Python lists into efficient NumPy arrays.

In [5]:
arr = np.array([1, 3, 5, 7, 9])

## Generating Evenly Spaced Integers
`np.arange(start, stop, step)` creates values from **start** to **stop (exclusive)** using the specified step size.

In [6]:
arr2 = np.arange(3, 10, 2)

## Generating Evenly Spaced Numbers
`np.linspace(start, stop, num)` generates a fixed number of evenly spaced values including both endpoints.

In [7]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Creating a Two-Dimensional Array
Passing a tuple to `np.ones()` creates a matrix. This example creates a **3×3** matrix filled with ones.

In [8]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Creating a Three-Dimensional Array
NumPy supports multidimensional arrays. This example creates a **2×2×2** array filled with zeros.

In [9]:
np.zeros((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

## Building a Matrix
This cell creates a 3×3 matrix that will be used to demonstrate indexing and modification.

In [10]:
arr3 = np.array(([4, 5, 6], [7, 8, 9], [10, 11, 12]))

## Modifying a Single Element
Individual elements can be accessed and updated using row and column indices.

In [11]:
arr3[1][1] = 1000
print(arr3)
arr3[1, 1] = 911
print(arr3)

[[   4    5    6]
 [   7 1000    9]
 [  10   11   12]]
[[  4   5   6]
 [  7 911   9]
 [ 10  11  12]]


## Replacing an Entire Row
Assigning to `arr[row]` replaces every value in that row.

In [12]:
arr3[0] = [1, 1, 1]
arr3

array([[  1,   1,   1],
       [  7, 911,   9],
       [ 10,  11,  12]])

## Replacing an Entire Column
The slicing syntax `:` selects all rows, allowing an entire column to be modified at once.

In [13]:
arr3[:, 2] = [0, 0, 0]
arr3

array([[  1,   1,   0],
       [  7, 911,   0],
       [ 10,  11,   0]])

## Random Floating-Point Numbers
`np.random.rand()` generates random values sampled from a uniform distribution over the interval [0, 1). Multiplying by 100 scales the range.

In [14]:
np.random.rand(2, 2, 2) * 100

array([[[47.48625969, 78.76022495],
        [32.77481332,  1.63894046]],

       [[61.23558187, 71.97265298],
        [88.48152383, 81.25104307]]])

## Reproducible Random Numbers
Using `np.random.seed()` fixes the random number generator so the same sequence is produced every time the notebook runs.

In [15]:
# np.random.seed(1) ==> this uses a fixed number for the seed so the output will always be the same. 
np.random.rand(3, 3) 

array([[0.32402588, 0.49589542, 0.64847741],
       [0.52336267, 0.22961822, 0.03187768],
       [0.36717449, 0.31651129, 0.06263171]])

## Random Numbers from Different Distributions
This section compares common NumPy random distributions such as the standard uniform and standard normal distributions.

In [16]:
# the default generation of random numbers is standard uniform distribution. 
# if we want normal distribution, we can use np.random.randn(3, 3) instead.

## Random Integers
`np.random.randint(low, high, size)` generates random integers in the specified range and shape.

In [17]:
np.random.randint(0, 10, (2, 3, 4))

array([[[3, 1, 3, 6],
        [0, 1, 3, 7],
        [0, 0, 6, 9]],

       [[7, 3, 4, 0],
        [6, 3, 1, 2],
        [7, 5, 9, 7]]], dtype=int32)

## Creating a Sample Array
A simple array is created for demonstrating arithmetic operations.

In [18]:
arr4 = np.arange(10)

## In-place Arithmetic
NumPy allows arithmetic operations to be applied directly to every element of an array without explicit loops.

In [19]:
arr4 += 1
arr4 = arr4 / 0.5
arr4

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## Vectorized Expressions
NumPy performs element-wise arithmetic efficiently, allowing complex mathematical expressions to be evaluated on entire arrays.

In [20]:
arr4 = arr4 * 5 + arr4 / 0.25
arr4

array([ 18.,  36.,  54.,  72.,  90., 108., 126., 144., 162., 180.])

## Boolean Indexing
Boolean masks allow selecting elements that satisfy specific conditions.

In [21]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)
print(a == b)
print(a >= 3)
print(b <= 3)

[False False False  True  True]
[False False  True  True  True]
[ True  True False False False]
[ True  True  True False False]
[False False  True False False]
[False False  True  True  True]
[False False  True  True  True]


## Aggregation Functions
Functions such as `min()`, `max()`, `mean()`, and `sum()` summarize an array's contents.

In [22]:
print(a[a >= b])
print(b[a <= 3])

[3 4 5]
[5 4 3]


## Statistical Operations
This section demonstrates several built-in statistical methods available for NumPy arrays.

In [23]:
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.std())

1
5
15
3.0
1.4142135623730951


## Dot Product
The dot product is a fundamental linear algebra operation used in machine learning, graphics, and scientific computing.

In [36]:
# dot production using numpy:
# works for vector-vector multiplication and matrix-vector multiplication and matrix-matrix multiplication.
# vector-vector: 
u = np.arange(5)
v = np.array([1, 3, 5, 7, 9])
print(u.dot(v))
U = np.arange(15)
U = U.reshape((3, 5))
print(U.dot(v))
V = np.arange(15)
V += 5
V *= 2
V = V.reshape((5, 3))
print(U.dot(V))

70
[ 70 195 320]
[[ 280  300  320]
 [ 830  900  970]
 [1380 1500 1620]]


## Identity Matrix
`np.eye(n)` creates an identity matrix containing ones on the main diagonal and zeros elsewhere.

In [40]:
# identity matrix using numpy: 
# square matrix mith ones on the main diagonal and zero on other cells.
# to create an n*n identity matrix, we use the eye function.
identity_3 = np.eye(3)
print(identity_3)
print(identity_3.dot(U))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]


## Matrix Inverse
`np.linalg.inv()` computes the inverse of a square matrix when it exists.

In [44]:
# matrix inverse using numpy:
# to calculate the inverse of a matrix using built-in numpy functions, we use linalg.inv function.
matrix1 = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(matrix1))
matrix2 = np.array([[1, 2], [2, 4]])
try:
    print(np.linalg.inv(matrix2))
except:
    print("the matrix does not have an inverse!")

[[-2.   1. ]
 [ 1.5 -0.5]]
the matrix does not have an inverse!
