In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
arr = np.array([1, 3, 5, 7, 9])

In [6]:
arr2 = np.arange(3, 10, 2)

In [7]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.zeros((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [10]:
arr3 = np.array(([4, 5, 6], [7, 8, 9], [10, 11, 12]))

In [11]:
arr3[1][1] = 1000
print(arr3)
arr3[1, 1] = 911
print(arr3)

[[   4    5    6]
 [   7 1000    9]
 [  10   11   12]]
[[  4   5   6]
 [  7 911   9]
 [ 10  11  12]]


In [12]:
arr3[0] = [1, 1, 1]
arr3

array([[  1,   1,   1],
       [  7, 911,   9],
       [ 10,  11,  12]])

In [13]:
arr3[:, 2] = [0, 0, 0]
arr3

array([[  1,   1,   0],
       [  7, 911,   0],
       [ 10,  11,   0]])

In [14]:
np.random.rand(2, 2, 2) * 100

array([[[26.55309097, 23.18183008],
        [21.36760111, 24.97770571]],

       [[94.49943358,  0.39559172],
        [76.95791838, 70.73985552]]])

In [15]:
# np.random.seed(1) ==> this uses a fixed number for the seed so the output will always be the same. 
np.random.rand(3, 3) 

array([[0.0317076 , 0.99631222, 0.78553916],
       [0.30194112, 0.34009227, 0.18981796],
       [0.60756721, 0.19468672, 0.92398537]])

In [16]:
# the default generation of random numbers is standard uniform distribution. 
# if we want normal distribution, we can use np.random.randn(3, 3) instead.

In [17]:
np.random.randint(0, 10, (2, 3, 4))

array([[[2, 5, 8, 0],
        [0, 0, 2, 2],
        [1, 6, 4, 9]],

       [[6, 3, 7, 4],
        [3, 5, 2, 3],
        [3, 0, 3, 7]]], dtype=int32)

In [18]:
arr4 = np.arange(10)

In [19]:
arr4 += 1
arr4 = arr4 / 0.5
arr4

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [20]:
arr4 = arr4 * 5 + arr4 / 0.25
arr4

array([ 18.,  36.,  54.,  72.,  90., 108., 126., 144., 162., 180.])

In [21]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)
print(a == b)
print(a >= 3)
print(b <= 3)

[False False False  True  True]
[False False  True  True  True]
[ True  True False False False]
[ True  True  True False False]
[False False  True False False]
[False False  True  True  True]
[False False  True  True  True]


In [22]:
print(a[a >= b])
print(b[a <= 3])

[3 4 5]
[5 4 3]


In [26]:
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.std())

1
5
15
3.0
1.4142135623730951
